# * native python configuration
[project]
name = "spoti-dl"
version = "2.0.0"
description = "spotidl: download songs, albums and playlists using Spotify links"
dependencies = ["spotipy", "python-dotenv"]
requires-python = ">=3.8"
license = { file = "LICENSE"}
readme = "README.md"
authors = [
    {name = "Dhruv Ahuja"}
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Multimedia :: Sound/Audio", 
    "Environment :: Console",
]

[project.urls]
repository = "https://github.com/dhruv-ahuja/spoti-dl/"

[project.optional-dependencies]
dev = ["black"]

# * rust configuration 
[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]
python-packages = ["spotidl"]
