[tool.poetry]
name = "yASD"
version = "1.0.6"
description = "yet Another Song Downloader- download songs, albums and playlists using Spotify links"
authors = ["Dhruv"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/good-times-ahead/yASD/"
repository = "https://github.com/good-times-ahead/yASD/"

[tool.poetry.dependencies]
python = "3.10"
spotipy = "^2.19.0"
yt-dlp = "^2021.12.27"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
yasd = "yasd.cli:controller"